CREATE TABLE IF NOT EXISTS user(
    'id' INTEGER PRIMARY KEY AUTOINCREMENT,
    'username' VARCHAR(100) NOT NULL,
    'password' VARCHAR(255) NOT NULL,
    'email' VARCHAR(255) NOT NULL,
    'created_at' TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    'updated_at' TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product(
    'id' INTEGER PRIMARY KEY AUTOINCREMENT,
    'name' VARCHAR(100) NOT NULL,
    'price' DECIMAL(10, 2) NOT NULL,
    'description' TEXT,
    'image' TEXT,
    'created_at' TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    'updated_at' TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cart(
    'id' INTEGER PRIMARY KEY AUTOINCREMENT,
    'user_id' INTEGER NOT NULL REFERENCES user(id),
    'created_at' TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    'updated_at' TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cart_product(
    'id' INTEGER PRIMARY KEY AUTOINCREMENT,
    'cart_id' INTEGER NOT NULL REFERENCES cart(id),
    'product_id' INTEGER NOT NULL REFERENCES product(id),
    'quantity' INTEGER NOT NULL,
    'created_at' TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    'updated_at' TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS 'order'(
    'id' INTEGER PRIMARY KEY AUTOINCREMENT,
    'user_id' INTEGER NOT NULL REFERENCES user(id),
    'cart_id' INTEGER NOT NULL REFERENCES cart(id),
    'total' DECIMAL(10, 2) NOT NULL,
    'created_at' TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    'updated_at' TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);