CREATE TABLE IF NOT EXISTS user(
    'id' INTEGER PRIMARY KEY AUTOINCREMENT,
    'username' VARCHAR(100) NOT NULL,
    'password' VARCHAR(255) NOT NULL,
    'email' VARCHAR(255) NOT NULL,
    'created_at' TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    'updated_at' TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)