ALTER TABLE movie_room ADD COLUMN is_3d BOOLEAN DEFAULT FALSE;
ALTER TABLE movie_room ADD COLUMN is_dbox BOOLEAN DEFAULT FALSE;
ALTER TABLE movie_room ADD COLUMN is_4dx BOOLEAN DEFAULT FALSE;
ALTER TABLE movie_room ADD COLUMN is_imax BOOLEAN DEFAULT FALSE;